### ISSUE TITLE
Shinpaugh Meeting Agenda

### ISSUE THREAD

**Issue by VaTechAstrobotics** [VTAstrobotics/PHOENIX#12]
Want to get his opinion on several things including:

- recruiting (should we try to onboard people ASAP or wait til the Sept 3rd Interest Meeting+ help with O Show?) **<5 min**
- discuss funding **<5 min**
- schedule weekly or (once every two weeks) meeting with shinpaugh **<10 min**
- mechanical project management **<25 min**
- controls project management and high level system review **<15 min**
- [OPTIONAL (can ignore)] GH teacher
- [OPTIONAL (can be email)] can he distribute our new technical poster (if/when we get branding approval)

**Comment by ThomasGiattino** [comment]
We should add the timeline to this. I think it is important Shinpaugh reviews our deadlines and prepares for 3 design reviews in his schedule. Also I think weekly leadership meetings with Shinpaugh should be held so we need to set that up. I disagree that it's optional for this meeting.

**Comment by H3nryM** [comment]
> Also I think weekly leadership meetings with Shinpaugh should be held so we need to set that up. I disagree that it's optional for this meeting.

YES CHEF 🫡

**Comment by H3nryM** [comment]
https://drive.google.com/file/d/1U9No8xYJKy8rR-z4fPZ0KbyFYdSPxBJL/view?usp=drive_link
