### ISSUE TITLE
Schedule Interest Meeting

### ISSUE THREAD

**Issue by VaTechAstrobotics** [VTAstrobotics/PHOENIX#15]
Sept 3rd. Time TBD

(just want to clarify that I cannot choose a time until the 6th day after the first day of classes because that's when reservation requests open for regular classrooms)

**Comment by theQuery** [comment]
I'd like to know a little more about what the issue is. I'm interested

**Comment by VaTechAstrobotics** [comment]
Lmao bruh. We're a university club. It's a meeting for students at Virginia Tech only, per membership requirements, sorry. How did you find this?

**Comment by theQuery** [comment]
I found it by searching the label "good first issue". It's what people usually search when they want to start contributing to open source. Apologies though

**Comment by VaTechAstrobotics** [comment]
Ohh lmao... sorry we don't have GitHub Team but want to use features so the repo has to be public :(

**Comment by theQuery** [comment]
That's alright, I'll leave you to it

**Comment by H3nryM** [comment]
8/26 1:30-2:30 in MCB 129
