### ISSUE TITLE
WL tour video

### ISSUE THREAD

**Issue by VaTechAstrobotics** [VTAstrobotics/PHOENIX#16]
Low effort video that shows off the WL and our bay including:

- Both front entrances
- Machine shop, weld shop
- Water fountain and bathrooms
- The general bay space (3D printers, drill press, test bot bench, electrical area, junk shelf, scrap bin, and shared tools (shelf + red toolbox))

The video shall not exceed 4 minutes 0 seconds.

**Comment by H3nryM** [comment]
https://youtu.be/F9_hkWRYJ18
