### ISSUE TITLE
Ware Lab Newsletter

### ISSUE THREAD

**Issue by VaTechAstrobotics** [VTAstrobotics/PHOENIX#20]
Per Dewey’s email, we need to create/curate some content for the Ware Lab newsletter.

- [x] [1-2 paragraph recap](https://docs.google.com/document/d/1FNT8AdaVaHpJ8CUQOCE7cQfufmfVcyfVKPfFIlhOqo0/edit) of the year including how we ranked out of how many teams.
- [x] 1-2 high definition photos
- [x] #21 

> Also, as your team finishes competitions for the year please provide me with a brief narrative (one or two paragraphs) on how you did along with two good high def (no low def please) photos of your team at the event(s). The newsletters get a lot of distribution to sponsors, Virginia Tech engineering departments and both lab communities so one or two paragraphs explaining how you did this year will help get the word out about your hard work. Please include how many schools or teams competed in your event and how you ranked overall. If you want to include details on how you did in static and dynamic events that would be great! Newsletters make for a great item to send to sponsors!

Note we placed 35th/49th at the NASA Lunar Robotics Mining Competition this year, and competed at the University of Alabama competition as well. I don’t personally know what place we finished there, but you can ask Thomas, Hayley, or Will.

**Comment by nerdygirl2004** [comment]
thomas i think you will be better suited for this project than i as you went to compo lol

**Comment by H3nryM** [comment]
Moving to in review until sent to Dewey

**Comment by H3nryM** [comment]
Oops. Sent a few days ago. He liked :)
