### ISSUE TITLE
Update Astrobotics on VT's site

### ISSUE THREAD

**Issue by VaTechAstrobotics** [VTAstrobotics/PHOENIX#24]
At https://eng.vt.edu/academics/student-teams/astrobotics.html, we have our own page on Virginia Tech’s domain, which may be a good place to find new members, idk.

To update it, use this Google Form: https://docs.google.com/forms/d/e/1FAIpQLSe-r1Ie50YkeCcTR3gDvv6tBmnD3D4V8py3EpBwpbBOLO9sXA/viewform

**Comment by nerdygirl2004** [comment]
I already submitted a updated version a few weeks ago but will wait till the new rules come out to update it again
