### ISSUE TITLE
2022-2023 Lessons Learned

### ISSUE THREAD

**Issue by VaTechAstrobotics** [VTAstrobotics/PHOENIX#5]
Everyone on leadership should review [this document](https://docs.google.com/document/d/1QP_o8eEzaJQUTUtYl_b73iXd2JAadwWj/edit), edit, add, etc. what they learned this past year that might be helpful going forward. **Check your box when you are satisfied with the document and have added all relevant lessons learned.**

- [x] Thomas
- [ ] Will
- [ ] Hayley
- [x] Henry
- [ ] Jack
- [ ] Anthony
- [ ] Caroline
- [x] Maddi

**Comment by H3nryM** [comment]
yall suck
