### ISSUE TITLE
Send WL Updated Budget

### ISSUE THREAD

**Issue by VaTechAstrobotics** [VTAstrobotics/PHOENIX#51]
Fill out [this spreadsheet](https://docs.google.com/spreadsheets/d/1yr0ya1MoVDPR4J-MJ2-rho6VwpPpo5pL/edit#gid=1425855989) with the WL's preferred budget formatting. Thomas - I think you should do this because only you know how much Dig spent last year. Everyone else put their spending on last year's [tracker](https://docs.google.com/spreadsheets/d/1_bJTaCtWNK5JZqh6JltEmY2BfcCKdAtU-xlCu0fC97E/edit#gid=0).

**Comment by H3nryM** [comment]
Sent on 8/1, dewey has not complained so I think we good
