### ISSUE TITLE
Send WL Updated Comp Info (recap)

### ISSUE THREAD

**Issue by VaTechAstrobotics** [VTAstrobotics/PHOENIX#52]
Very easy, just fill [this sheet](https://docs.google.com/spreadsheets/d/1WI3X3zrQcGQrFXU1D-_3oeuMiBdXJ23S/edit#gid=1705536997) out. Let me (Henry) know when you're done and I can send to Dewey.

**Comment by H3nryM** [comment]
Sent on 8/1, dewey has not complained so I think we good
