### ISSUE TITLE
Document how to use the GitHub Wiki

### ISSUE THREAD

**Issue by VaTechAstrobotics** [VTAstrobotics/PHOENIX#57]

**Comment by H3nryM** [comment]
You know I realize that this is going to be a WIP thing for a very, very long time. I'm not satisfied to mark this as done just yet, but the meta docs have quite a ways to go.

**Comment by H3nryM** [comment]
tbh i didnt do much since that comment, but I'm out of time. it's good enough to close, and it will be a WIP forever
