### ISSUE TITLE
New Project Name

### ISSUE THREAD

**Issue by VaTechAstrobotics** [VTAstrobotics/PHOENIX#60]
PHOENIX was taken by 2018 Astro, but that's ok it wasn't that good anyway.

Must be done before the first day of classes for several dependent tasks. If nothing suggested, we are sticking with PHOENIX despite it being used already. I mean the whole idea is that the team died and was reborn from the ashes, so it kind of makes sense.

**Comment by H3nryM** [comment]
phoenix it is
