### ISSUE TITLE
Documentation Directory

### ISSUE THREAD

**Issue by VaTechAstrobotics** [VTAstrobotics/PHOENIX#62]
No one knows where, if anywhere, things have been documented. This has caused a _lot_ of repeated work. Figure out the best place for an all-encompassing directory for the docs.

Long term, this may just be a _really_ good part of the team website, which can house all the documentation as well.

**Update:** it's looking like the GH Wiki Sidebar will serve this purpose. It can be customized quite a bit, and a basic template is already up.

**Comment by H3nryM** [comment]
The documentation directory will both be the GitHub Wikis sidebar **and** the "How To Find Stuff" heading under the "How To Use (START HERE!)" page.
