### ISSUE TITLE
Technical Poster Design

### ISSUE THREAD

**Issue by VaTechAstrobotics** [VTAstrobotics/PHOENIX#67]
This is a poster to be displayed outside the Ware Lab bay to display technical details about our robot. Formula has a pretty good one, but imo it's not very good looking. Jack likes the appearance tho, so maybe personal pref

**Comment by nerdygirl2004** [comment]
This for outside the ware lab, like a project poster per say

**Comment by H3nryM** [comment]
youre the best ty

**Comment by H3nryM** [comment]
https://drive.google.com/file/d/1CLoIuKBNWbCtMuuNvydQ-gOG2uBVwrBu/view?usp=drive_link
