### ISSUE TITLE
Google Drive Structure

### ISSUE THREAD

**Issue by VaTechAstrobotics** [VTAstrobotics/PHOENIX#8]
From Trello:
I’m not saying create 30 folders, im saying to figure out the ideal Drive _structure_.

How will we break up folders? Should mech/controls have its own folder? Or straight to subteams? Where do the rationales go? Should they be all grouped in one massive folder, or broken by subteam? Where does documentation go? Etc.

Obviously a critical task that will set the team up to either succeed or fail, depending on quality of decisions.

**Comment by H3nryM** [comment]
Still a super important thing IMO but it's fallen onto the backburner until I get time. In other words, it may end up just... half-organized as usual.
