### ISSUE TITLE
QR Codes on the Bay

### ISSUE THREAD

**Issue by H3nryM** [VTAstrobotics/PHOENIX#84]
I want at least two links QR-coded and **on the bay**, somehow. They can be part of a poster, literally a piece of 8.5x11 paper with what the QR code links to and the code itself, or something unique (see potential ideas below). **Include the link below the QR code in case someone has trouble scanning it.**

QR1: Link to video explaining what the team does https://www.youtube.com/watch?v=FW6O6FGgrts
QR2: Link to interest form https://forms.gle/9WhY7d5dvY5FdqYD9

**OPTIONAL:** Make the QR-codes really cool and unique. This will _really_ make our club, and the codes themselves, stand out and more likely to be scanned.
_Ideas to get you started:_ One cool thing we did in high school was use a laser cutter to rastorize a QR code onto wood. So it burned the wood for the black squares and left it alone for the white squares. Lots of ideas here, cutting out of scrap metal on the waterjet (painting the metal black and putting it on a white background), 3D printing a 3D QR code maybe? Tons of ideas, can ask mech ppl like Jack or Anthony or come up with more yourself.

**Comment by nerdygirl2004** [comment]
[QR Codes Document.pdf](https://github.com/VTAstrobotics/PHOENIX/files/12270461/QR.Codes.Document.pdf)
